[build]
  command = "npm install && npm run build"
  publish = "static"
  functions = "functions"
  base = "/"

[[redirects]]
  from = "/"
  to = "/login"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404-error"
  status = 200